### ISSUE TITLE
Migrate test suite to GitHub Actions

### ISSUE THREAD

**Issue by SeanTAllen** [disposable-email-domains/python-disposable-email-domains#71]
It's been a while since there was a release and the source list has added many domains.

Is there any chance of getting a new release?

**Comment by di** [comment]
Looks like our travis-ci integration broke when this project moved to the https://github.com/disposable-email-domains org, will try and re-enable it.

**Comment by SeanTAllen** [comment]
Awesome. 

I know that Travis mostly (completely?) shut down the free open source support. If you end up needing to switch to GitHub actions, I'd be happy to assist.

**Comment by di** [comment]
Yeah, I think that might be necessary, please feel free to work on it!

**Comment by di** [comment]
I added the secrets to the repo as `PYPI_API_TOKEN` and `OAUTH_TOKEN`.

**Comment by SeanTAllen** [comment]
@di After looking at the existing travis, I realized I don't know enough about pypi to do it all, but I can do the plumbing around it and a decent chunk of the pypi.

The travis deploy provider pypi stuff, does that build and deploy? It appears to, but I'm not sure.

Also, it appears that travis was triggered via a cron facility- how often should it run? (i'm looking at check_for_differences)

**Comment by di** [comment]
Great questions! The cron job is triggered 1x a day. For the deployment, that should probably use https://github.com/pypa/gh-action-pypi-publish instead, which will pick up on the `PYPI_API_TOKEN` secret automatically.

**Comment by SeanTAllen** [comment]
does check_for_differences do the building? if yes, I should be able to get a large chunk of it done and you might have to clean up around the edges where I'm ignorant of pypi specifics.

**Comment by di** [comment]
No, this bit handles the building & deploying on Travis:

https://github.com/disposable-email-domains/python-disposable-email-domains/blob/c1766e5e28d3409a3e423885e191921c666eb1eb/.travis.yml#L25-L30

The PyPI github action will handle it all for you as well, so you shouldn't need to configure it.

There's basically three steps for the CI flow here:
1. run the tests across multiple travis versions (pass/fail)
2. check if there's any difference between what this library has and the source repo
    1. if there is a difference:
         1. if it's not the cron-job, fail: there shouldn't be differences
        0. if it is the cron-job, pull in the changes, bump the version and open a PR on this repo
    0. if there isn't a difference, pass
3. if everything above passes, run the deployment

1 and 2 should only happen for PRs. 3 should only happen with the cron job.

**Comment by SeanTAllen** [comment]
So it should deploy on PR being opened?

**Comment by di** [comment]
Another great question: no. Travis skips the deployment phase if the branch isn't the master/main branch, e.g. https://travis-ci.com/github/disposable-email-domains/python-disposable-email-domains/jobs/510915511 says "Skipping a deployment with the pypi provider because this branch is not permitted: version-0.0.65"

There's a similar setting for GitHub actions: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

So we'll probably want at least two workflows, one for the tests and another for the deployment step.

**Comment by SeanTAllen** [comment]
There's definitely gaps in my knowledge and understanding of how you do it, but I'll put together something that can be a starting point. To be clear, the deployment is...

- use check_for_differences to see if there are differences.
- if yes, do the deployment.

yes?

**Comment by di** [comment]
Yep!

**Comment by di** [comment]
Also, I was able to get things working again and make a new release: https://pypi.org/project/disposable-email-domains/0.0.65/

So I'll rename this issue to be about porting to Actions, due to the travis-ci.org shutdown that's now happening on on June 15th.
